### ISSUE TITLE
Участие в переводе

### ISSUE THREAD

**Issue by Bolik** [fhir-ru/fhir-ru.github.io#2]
Добрый день,

хотел бы поучаствовать в переводе стандарта. Опишите, пожалуйста, процедуру - какие инструменты использовать, куда вносить изменения?

**Comment by Semalexa** [comment]
Здравствуйте, Алексей,
отправила вам приглашение в репозиторий с переводом https://github.com/fhir-ru/fhir-svn. Весь перевод в основном лежит в папочке source.ru, которая является копией английской версии source. Каждый FHIR-ресурс лежит в своей соответствующей папочке, переводить обычно нужно файлы вида <название_ресурса>-introduction.xml, <название_ресурса>-notes.xml и <название_ресурса>-spreadsheet.xml. В корне папочки source.ru лежат html-ные файлы документации FHIR и разные вспомогательные файлы.
Сайт с переводом спецификации билдится по пушу в репозиторий, билдится ~40 минут. Статус сборки можно смотреть в Тревисе https://travis-ci.org/fhir-ru/fhir-svn/builds. Адрес самого сайта -  http://fhir-ru.github.io.
Чтобы не конфликтовать, можно отмечать в трекере на гитхабе, какой ресурс или страницу вы переводите в данный момент, добавив таск с названием ресурса или страницы и пометив его меткой In Progress.
Можно будет созвониться в понедельник, я расскажу более подробно.

С уважением,
Александра Павлышина

**Comment by Bolik** [comment]
Я бы хотел для начала позаниматься корректорской работой - поскольку я пока не очень силен в предметной области. Поэтому у меня будет куча мелких правок во многих файлах - как это лучше организовать? Делать pull request?

**Comment by Semalexa** [comment]
Алексей, как вам будет удобнее. Я выслала вам приглашение в репозиторий с
переводом https://github.com/fhir-ru/fhir-svn. Если хотите, давайте
попробуем через pull request, но вы можете скачать себе проект и делать
коммиты в мастер.

---
Sincerely,
Alexandra
semalex05@gmail.com

2016-04-04 12:23 GMT+03:00 Alexey Slynko <notifications@github.com>:

**Comment by Bolik** [comment]
Александра,
пытаюсь сделать сборку, запустив ./build-russian.sh

выдает следующую ошибку (кусочек из лога):

[java]  ...vocab #1                                                               0.001  41sec  203MB
     [java]   ERROR: Unable to process warnings: Error unmarshalling resource: No Database Connections Available for "Operation/ConformanceStmt" (used: InUse 100 of 100: BuildIndexes 69hr (select ClosureEntryKey, Closures.ClosureKey, SubsumesKey, Name, URL, Code from ClosureEntries, Concepts, Closures where Closures.ClosureKey = ClosureEntries.ClosureKey and ClosureEntries.IndexedVersion = 0 and ClosureEntries.SubsumesKey = Concepts.ConceptKey),BuildIndexes 69hr (update Closures set Version = 21 where ClosureKey = 46),BuildIndexes 69hr (Delete from ValueSetMembers where ValueSetKey = 6 and ConceptKey = 889),Operation/Create 68hr (insert into ClosureEntries (ClosureEntryKey, ClosureKey, SubsumesKey, SubsumedKey, IndexedVersion) values (1471, 46, 891, 891, 0)),Operation/Transaction 67hr (select Ids.ResourceKey, Deleted from Ids, Types where Ids.id = :s and Ids.ResourceTypeKey = Types.ResourceTypeKey and Supported = 1 and ResourceName = :n),fhir 65hr (select ResourceName, count(*) as Count from Ids, Types where Ids.ResourceTypeKey = Types.ResourceTypeKey group by ResourceName),fhir 65hr (select ResourceName, count(*) as Count from Ids, Types where Ids.ResourceTypeKey = Types.ResourceTypeKey group by ResourceName),Operation/Search 65hr (select ResourceTypeKey from Types where supported = 1 and ResourceName = 'Patient'),Operation/Search 65hr (select ResourceTypeKey from Types where supported = 1 and ResourceName = 'StructureDefinition'),Operation/Search 65hr (select ResourceTypeKey from Types where supported = 1 and ResourceName = 'StructureDefinition'),Operation/Search 65hr (select ResourceTypeKey from Types where supported = 1 and ResourceName = 'StructureDefinition'),Operation/Search 65hr (select ResourceTypeKey from Types where supported = 1 and ResourceName = 'StructureDefinition'),Operation/Search 65hr (select ResourceTypeKey from Types where supported = 1 and ResourceName = 'StructureDefinition'),Operation/Search 65hr (select ResourceTypeKey from Types where supported = 1 and ResourceName = 'StructureDefinition'),Operation/Search 64hr (select ResourceTypeKey from Types where supported = 1 and ResourceName = 'StructureDefinition'),Operation/Search 64hr (select ResourceTypeKey from Types where supported = 1 and ResourceName = 'StructureDefinition'),Operation/Operation 64hr (),Operation/Operation 64hr (),Operation/Operation 64hr (),Operation/Operation 64hr (),Operation/Operation 64hr (),Operation/Operation 64hr (),Operation/Operation 64hr (select Ids.ResourceKey, Deleted from Ids, Types where Ids.id = :s and Ids.ResourceTypeKey = Types.ResourceTypeKey and Supported = 1 and ResourceName = :n),Operation/Search 64hr (select ResourceTypeKey from Types where supported = 1 and ResourceName = 'StructureDefinition'),Operation/Search 64hr (select ResourceTypeKey from Types where supported = 1 and ResourceName = 'StructureDefinition'),Operation/Search 64hr (select ResourceTypeKey from Types where supported = 1 and ResourceName = 'StructureDefinition'),Operation/Search 64hr (select ResourceTypeKey from Types where supported = 1 and ResourceName = 'StructureDefinition'),Operation/Search 64hr (select ResourceTypeKey from Types where supported = 1 and ResourceName = 'StructureDefinition'),Operation/Search 64hr (select ResourceTypeKey from Types where supported = 1 and ResourceName = 'StructureDefinition'),Operation/Search 64hr (select ResourceTypeKey from Types where supported = 1 and ResourceName = 'StructureDefinition'),Operation/Search 64hr (select ResourceTypeKey from Types where supported = 1 and ResourceName = 'StructureDefinition'),Operation/Search 64hr (select ResourceTypeKey from Types where supported = 1 and ResourceName = 'Patient'),Operation/Read 64hr (select Ids.ResourceKey, Deleted from Ids, Types where Ids.id = :s and Ids.ResourceTypeKey = Types.ResourceTypeKey and Supported = 1 and ResourceName = :n),fhir 64hr (select ResourceName, count(*) as Count from Ids, Types where Ids.ResourceTypeKey = Types.ResourceTypeKey group by ResourceName),Operation/Operation 64hr (),Operation/Operation 64hr (),Operation/Operation 64hr (),Operation/Operation 64hr (),Operation/Operation 64hr (),Operation/Operation 64hr (),Operation/Operation 64hr (),Operation/Operation 64hr (),Operation/Operation 64hr (),Operation/Operation 64hr (),Operation/Operation 64hr (),Operation/Operation 63hr (),Operation/Operation 63hr (),Operation/Operation 63hr (),Operation/Operation 63hr (),Operation/Read 62hr (select Ids.ResourceKey, Deleted from Ids, Types where Ids.id = :s and Ids.ResourceTypeKey = Types.ResourceTypeKey and Supported = 1 and ResourceName = :n),Operation/Read 61hr (select Ids.ResourceKey, Deleted from Ids, Types where Ids.id = :s and Ids.ResourceTypeKey = Types.ResourceTypeKey and Supported = 1 and ResourceName = :n),Operation/Search 60hr (select ResourceTypeKey from Types where supported = 1 and ResourceName = 'Organization'),Operation/Search 60hr (select ResourceTypeKey from Types where supported = 1 and ResourceName = 'Patient'),Operation/Operation 58hr (),Operation/Operation 57hr (),Operation/Operation 57hr (),Operation/Operation 57hr (),Operation/Operation 57hr (select Ids.ResourceKey, Deleted from Ids, Types where Ids.id = :s and Ids.ResourceTypeKey = Types.ResourceTypeKey and Supported = 1 and ResourceName = :n),Operation/Search 57hr (select ResourceTypeKey from Types where supported = 1 and ResourceName = 'Patient'),Operation/Read 55hr (select Ids.ResourceKey, Deleted from Ids, Types where Ids.id = :s and Ids.ResourceTypeKey = Types.ResourceTypeKey and Supported = 1 and ResourceName = :n),Operation/Read 55hr (select Ids.ResourceKey, Deleted from Ids, Types where Ids.id = :s and Ids.ResourceTypeKey = Types.ResourceTypeKey and Supported = 1 and ResourceName = :n),Operation/Read 55hr (select Ids.ResourceKey, Deleted from Ids, Types where Ids.id = :s and Ids.ResourceTypeKey = Types.ResourceTypeKey and Supported = 1 and ResourceName = :n),Operation/Search 55hr (select ResourceTypeKey from Types where supported = 1 and ResourceName = 'DiagnosticReport'),Operation/Search 55hr (select ResourceTypeKey from Types where supported = 1 and ResourceName = 'DiagnosticReport'),Operation/Search 55hr (select ResourceTypeKey from Types where supported = 1 and ResourceName = 'DiagnosticReport'),Operation/Read 55hr (select Ids.ResourceKey, Deleted from Ids, Types where Ids.id = :s and Ids.ResourceTypeKey = Types.ResourceTypeKey and Supported = 1 and ResourceName = :n),Operation/Read 55hr (select Ids.ResourceKey, Deleted from Ids, Types where Ids.id = :s and Ids.ResourceTypeKey = Types.ResourceTypeKey and Supported = 1 and ResourceName = :n),Operation/Create 55hr (),Operation/Read 55hr (select Ids.ResourceKey, Deleted from Ids, Types where Ids.id = :s and Ids.ResourceTypeKey = Types.ResourceTypeKey and Supported = 1 and ResourceName = :n),Operation/Operation 55hr (select Ids.ResourceKey, Deleted from Ids, Types where Ids.id = :s and Ids.ResourceTypeKey = Types.ResourceTypeKey and Supported = 1 and ResourceName = :n),Operation/Operation 55hr (Select Kind, Uri, Code, Display, (select count(*) from VersionTags where Tags.TagKey = VersionTags.TagKey and ResourceVersionKey in (select MostRecent from Ids)) as usecount from Tags where TagKey in (Select TagKey from VersionTags where ResourceVersionKey in (select MostRecent from Ids)) order by Kind, Uri, Code),Operation/Search 55hr (select ResourceTypeKey from Types where supported = 1 and ResourceName = 'Patient'),Operation/Create 55hr (),Operation/Read 55hr (select Ids.ResourceKey, Deleted from Ids, Types where Ids.id = :s and Ids.ResourceTypeKey = Types.ResourceTypeKey and Supported = 1 and ResourceName = :n),Operation/Read 55hr (select Ids.ResourceKey, Deleted from Ids, Types where Ids.id = :s and Ids.ResourceTypeKey = Types.ResourceTypeKey and Supported = 1 and ResourceName = :n),Operation/Read 55hr (select Ids.ResourceKey, Deleted from Ids, Types where Ids.id = :s and Ids.ResourceTypeKey = Types.ResourceTypeKey and Supported = 1 and ResourceName = :n),Operation/Operation 55hr (select Ids.ResourceKey, Deleted from Ids, Types where Ids.id = :s and Ids.ResourceTypeKey = Types.ResourceTypeKey and Supported = 1 and ResourceName = :n),Operation/Operation 55hr (select Ids.ResourceKey, Deleted from Ids, Types where Ids.id = :s and Ids.ResourceTypeKey = Types.ResourceTypeKey and Supported = 1 and ResourceName = :n),Operation/Read 55hr (select Ids.ResourceKey, Deleted from Ids, Types where Ids.id = :s and Ids.ResourceTypeKey = Types.ResourceTypeKey and Supported = 1 and ResourceName = :n),Operation/Operation 54hr (),Operation/Read 54hr (select Ids.ResourceKey, Deleted from Ids, Types where Ids.id = :s and Ids.ResourceTypeKey = Types.ResourceTypeKey and Supported = 1 and ResourceName = :n),Operation/Operation 53hr (select Ids.ResourceKey, Deleted from Ids, Types where Ids.id = :s and Ids.ResourceTypeKey = Types.ResourceTypeKey and Supported = 1 and ResourceName = :n),Operation/Read 53hr (select Ids.ResourceKey, Deleted from Ids, Types where Ids.id = :s and Ids.ResourceTypeKey = Types.ResourceTypeKey and Supported = 1 and ResourceName = :n),fhir 52hr (select ResourceName, count(*) as Count from Ids, Types where Ids.ResourceTypeKey = Types.ResourceTypeKey group by ResourceName),fhir 52hr (select ResourceName, count(*) as Count from Ids, Types where Ids.ResourceTypeKey = Types.ResourceTypeKey group by ResourceName),fhir 51hr (select ResourceName, count(*) as Count from Ids, Types where Ids.ResourceTypeKey = Types.ResourceTypeKey group by ResourceName),Operation/Search 51hr (select ResourceTypeKey from Types where supported = 1 and ResourceName = 'NamingSystem'),Operation/Read 51hr (select Ids.ResourceKey, Deleted from Ids, Types where Ids.id = :s and Ids.ResourceTypeKey = Types.ResourceTypeKey and Supported = 1 and ResourceName = :n),Operation/Read 50hr (select Ids.ResourceKey, Deleted from Ids, Types where Ids.id = :s and Ids.ResourceTypeKey = Types.ResourceTypeKey and Supported = 1 and ResourceName = :n),Operation/Search 49hr (select ResourceTypeKey from Types where supported = 1 and ResourceName = 'DiagnosticReport'),fhir 49hr (select ResourceName, count(*) as Count from Ids, Types where Ids.ResourceTypeKey = Types.ResourceTypeKey group by ResourceName),fhir 49hr (select ResourceName, count(*) as Count from Ids, Types where Ids.ResourceTypeKey = Types.ResourceTypeKey group by ResourceName),fhir 49hr (select ResourceName, count(*) as Count from Ids, Types where Ids.ResourceTypeKey = Types.ResourceTypeKey group by ResourceName),fhir 49hr (select ResourceName, count(*) as Count from Ids, Types where Ids.ResourceTypeKey = Types.ResourceTypeKey group by ResourceName),fhir 49hr (select ResourceName, count(*) as Count from Ids, Types where Ids.ResourceTypeKey = Types.ResourceTypeKey group by ResourceName),fhir 48hr (select ResourceName, count(*) as Count from Ids, Types where Ids.ResourceTypeKey = Types.ResourceTypeKey group by ResourceName),fhir 48hr (select ResourceName, count(*) as Count from Ids, Types where Ids.ResourceTypeKey = Types.ResourceTypeKey group by ResourceName),Operation/Read 48hr (select Ids.ResourceKey, Deleted from Ids, Types where Ids.id = :s and Ids.ResourceTypeKey = Types.ResourceTypeKey and Supported = 1 and ResourceName = :n),Operation/Operation 47hr (),Operation/Search 47hr (select ResourceTypeKey from Types where supported = 1 and ResourceName = 'Patient'))
[java]  ...vocab #1                                                               0.001  41sec  203MB
     [java]   ERROR: Unable to process warnings: Error unmarshalling resource: No Database Connections Available for "Operation/ConformanceStmt" (used: InUse 100 of 100: BuildIndexes 69hr (select ClosureEntryKey, Closures.ClosureKey, SubsumesKey, Name, URL, Code from ClosureEntries, Concepts, Closures where Closures.ClosureKey = ClosureEntries.ClosureKey and ClosureEntries.IndexedVersion = 0 and ClosureEntries.SubsumesKey = Concepts.ConceptKey),BuildIndexes 69hr (update Closures set Version = 21 where ClosureKey = 46),BuildIndexes 69hr (Delete from ValueSetMembers where ValueSetKey = 6 and ConceptKey = 889),Operation/Create 68hr (insert into ClosureEntries (ClosureEntryKey, ClosureKey, SubsumesKey, SubsumedKey, IndexedVersion) values (1471, 46, 891, 891, 0)),Operation/Transaction 67hr (select Ids.ResourceKey, Deleted from Ids, Types where Ids.id = :s and Ids.ResourceTypeKey = Types.ResourceTypeKey and Supported = 1 and ResourceName = :n),fhir 65hr (select ResourceName, count(*) as Count from Ids, Types where Ids.ResourceTypeKey = Types.ResourceTypeKey group by ResourceName),fhir 65hr (select ResourceName, count(*) as Count from Ids, Types where Ids.ResourceTypeKey = Types.ResourceTypeKey group by ResourceName),Operation/Search 65hr (select ResourceTypeKey from Types where supported = 1 and ResourceName = 'Patient'),Operation/Search 65hr (select ResourceTypeKey from Types where supported = 1 and ResourceName = 'StructureDefinition'),Operation/Search 65hr (select ResourceTypeKey from Types where supported = 1 and ResourceName = 'StructureDefinition'),Operation/Search 65hr (select ResourceTypeKey from Types where supported = 1 and ResourceName = 'StructureDefinition'),Operation/Search 65hr (select ResourceTypeKey from Types where supported = 1 and ResourceName = 'StructureDefinition'),Operation/Search 65hr (select ResourceTypeKey from Types where supported = 1 and ResourceName = 'StructureDefinition'),Operation/Search 65hr (select ResourceTypeKey from Types where supported = 1 and ResourceName = 'StructureDefinition'),Operation/Search 64hr (select ResourceTypeKey from Types where supported = 1 and ResourceName = 'StructureDefinition'),Operation/Search 64hr (select ResourceTypeKey from Types where supported = 1 and ResourceName = 'StructureDefinition'),Operation/Operation 64hr (),Operation/Operation 64hr (),Operation/Operation 64hr (),Operation/Operation 64hr (),Operation/Operation 64hr (),Operation/Operation 64hr (),Operation/Operation 64hr (select Ids.ResourceKey, Deleted from Ids, Types where Ids.id = :s and Ids.ResourceTypeKey = Types.ResourceTypeKey and Supported = 1 and ResourceName = :n),Operation/Search 64hr (select ResourceTypeKey from Types where supported = 1 and ResourceName = 'StructureDefinition'),Operation/Search 64hr (select ResourceTypeKey from Types where supported = 1 and ResourceName = 'StructureDefinition'),Operation/Search 64hr (select ResourceTypeKey from Types where supported = 1 and ResourceName = 'StructureDefinition'),Operation/Search 64hr (select ResourceTypeKey from Types where supported = 1 and ResourceName = 'StructureDefinition'),Operation/Search 64hr (select ResourceTypeKey from Types where supported = 1 and ResourceName = 'StructureDefinition'),Operation/Search 64hr (select ResourceTypeKey from Types where supported = 1 and ResourceName = 'StructureDefinition'),Operation/Search 64hr (select ResourceTypeKey from Types where supported = 1 and ResourceName = 'StructureDefinition'),Operation/Search 64hr (select ResourceTypeKey from Types where supported = 1 and ResourceName = 'StructureDefinition'),Operation/Search 64hr (select ResourceTypeKey from Types where supported = 1 and ResourceName = 'Patient'),Operation/Read 64hr (select Ids.ResourceKey, Deleted from Ids, Types where Ids.id = :s and Ids.ResourceTypeKey = Types.ResourceTypeKey and Supported = 1 and ResourceName = :n),fhir 64hr (select ResourceName, count(*) as Count from Ids, Types where Ids.ResourceTypeKey = Types.ResourceTypeKey group by ResourceName),Operation/Operation 64hr (),Operation/Operation 64hr (),Operation/Operation 64hr (),Operation/Operation 64hr (),Operation/Operation 64hr (),Operation/Operation 64hr (),Operation/Operation 64hr (),Operation/Operation 64hr (),Operation/Operation 64hr (),Operation/Operation 64hr (),Operation/Operation 64hr (),Operation/Operation 63hr (),Operation/Operation 63hr (),Operation/Operation 63hr (),Operation/Operation 63hr (),Operation/Read 62hr (select Ids.ResourceKey, Deleted from Ids, Types where Ids.id = :s and Ids.ResourceTypeKey = Types.ResourceTypeKey and Supported = 1 and ResourceName = :n),Operation/Read 61hr (select Ids.ResourceKey, Deleted from Ids, Types where Ids.id = :s and Ids.ResourceTypeKey = Types.ResourceTypeKey and Supported = 1 and ResourceName = :n),Operation/Search 60hr (select ResourceTypeKey from Types where supported = 1 and ResourceName = 'Organization'),Operation/Search 60hr (select ResourceTypeKey from Types where supported = 1 and ResourceName = 'Patient'),Operation/Operation 58hr (),Operation/Operation 57hr (),Operation/Operation 57hr (),Operation/Operation 57hr (),Operation/Operation 57hr (select Ids.ResourceKey, Deleted from Ids, Types where Ids.id = :s and Ids.ResourceTypeKey = Types.ResourceTypeKey and Supported = 1 and ResourceName = :n),Operation/Search 57hr (select ResourceTypeKey from Types where supported = 1 and ResourceName = 'Patient'),Operation/Read 55hr (select Ids.ResourceKey, Deleted from Ids, Types where Ids.id = :s and Ids.ResourceTypeKey = Types.ResourceTypeKey and Supported = 1 and ResourceName = :n),Operation/Read 55hr (select Ids.ResourceKey, Deleted from Ids, Types where Ids.id = :s and Ids.ResourceTypeKey = Types.ResourceTypeKey and Supported = 1 and ResourceName = :n),Operation/Read 55hr (select Ids.ResourceKey, Deleted from Ids, Types where Ids.id = :s and Ids.ResourceTypeKey = Types.ResourceTypeKey and Supported = 1 and ResourceName = :n),Operation/Search 55hr (select ResourceTypeKey from Types where supported = 1 and ResourceName = 'DiagnosticReport'),Operation/Search 55hr (select ResourceTypeKey from Types where supported = 1 and ResourceName = 'DiagnosticReport'),Operation/Search 55hr (select ResourceTypeKey from Types where supported = 1 and ResourceName = 'DiagnosticReport'),Operation/Read 55hr (select Ids.ResourceKey, Deleted from Ids, Types where Ids.id = :s and Ids.ResourceTypeKey = Types.ResourceTypeKey and Supported = 1 and ResourceName = :n),Operation/Read 55hr (select Ids.ResourceKey, Deleted from Ids, Types where Ids.id = :s and Ids.ResourceTypeKey = Types.ResourceTypeKey and Supported = 1 and ResourceName = :n),Operation/Create 55hr (),Operation/Read 55hr (select Ids.ResourceKey, Deleted from Ids, Types where Ids.id = :s and Ids.ResourceTypeKey = Types.ResourceTypeKey and Supported = 1 and ResourceName = :n),Operation/Operation 55hr (select Ids.ResourceKey, Deleted from Ids, Types where Ids.id = :s and Ids.ResourceTypeKey = Types.ResourceTypeKey and Supported = 1 and ResourceName = :n),Operation/Operation 55hr (Select Kind, Uri, Code, Display, (select count(*) from VersionTags where Tags.TagKey = VersionTags.TagKey and ResourceVersionKey in (select MostRecent from Ids)) as usecount from Tags where TagKey in (Select TagKey from VersionTags where ResourceVersionKey in (select MostRecent from Ids)) order by Kind, Uri, Code),Operation/Search 55hr (select ResourceTypeKey from Types where supported = 1 and ResourceName = 'Patient'),Operation/Create 55hr (),Operation/Read 55hr (select Ids.ResourceKey, Deleted from Ids, Types where Ids.id = :s and Ids.ResourceTypeKey = Types.ResourceTypeKey and Supported = 1 and ResourceName = :n),Operation/Read 55hr (select Ids.ResourceKey, Deleted from Ids, Types where Ids.id = :s and Ids.ResourceTypeKey = Types.ResourceTypeKey and Supported = 1 and ResourceName = :n),Operation/Read 55hr (select Ids.ResourceKey, Deleted from Ids, Types where Ids.id = :s and Ids.ResourceTypeKey = Types.ResourceTypeKey and Supported = 1 and ResourceName = :n),Operation/Operation 55hr (select Ids.ResourceKey, Deleted from Ids, Types where Ids.id = :s and Ids.ResourceTypeKey = Types.ResourceTypeKey and Supported = 1 and ResourceName = :n),Operation/Operation 55hr (select Ids.ResourceKey, Deleted from Ids, Types where Ids.id = :s and Ids.ResourceTypeKey = Types.ResourceTypeKey and Supported = 1 and ResourceName = :n),Operation/Read 55hr (select Ids.ResourceKey, Deleted from Ids, Types where Ids.id = :s and Ids.ResourceTypeKey = Types.ResourceTypeKey and Supported = 1 and ResourceName = :n),Operation/Operation 54hr (),Operation/Read 54hr (select Ids.ResourceKey, Deleted from Ids, Types where Ids.id = :s and Ids.ResourceTypeKey = Types.ResourceTypeKey and Supported = 1 and ResourceName = :n),Operation/Operation 53hr (select Ids.ResourceKey, Deleted from Ids, Types where Ids.id = :s and Ids.ResourceTypeKey = Types.ResourceTypeKey and Supported = 1 and ResourceName = :n),Operation/Read 53hr (select Ids.ResourceKey, Deleted from Ids, Types where Ids.id = :s and Ids.ResourceTypeKey = Types.ResourceTypeKey and Supported = 1 and ResourceName = :n),fhir 52hr (select ResourceName, count(*) as Count from Ids, Types where Ids.ResourceTypeKey = Types.ResourceTypeKey group by ResourceName),fhir 52hr (select ResourceName, count(*) as Count from Ids, Types where Ids.ResourceTypeKey = Types.ResourceTypeKey group by ResourceName),fhir 51hr (select ResourceName, count(*) as Count from Ids, Types where Ids.ResourceTypeKey = Types.ResourceTypeKey group by ResourceName),Operation/Search 51hr (select ResourceTypeKey from Types where supported = 1 and ResourceName = 'NamingSystem'),Operation/Read 51hr (select Ids.ResourceKey, Deleted from Ids, Types where Ids.id = :s and Ids.ResourceTypeKey = Types.ResourceTypeKey and Supported = 1 and ResourceName = :n),Operation/Read 50hr (select Ids.ResourceKey, Deleted from Ids, Types where Ids.id = :s and Ids.ResourceTypeKey = Types.ResourceTypeKey and Supported = 1 and ResourceName = :n),Operation/Search 49hr (select ResourceTypeKey from Types where supported = 1 and ResourceName = 'DiagnosticReport'),fhir 49hr (select ResourceName, count(*) as Count from Ids, Types where Ids.ResourceTypeKey = Types.ResourceTypeKey group by ResourceName),fhir 49hr (select ResourceName, count(*) as Count from Ids, Types where Ids.ResourceTypeKey = Types.ResourceTypeKey group by ResourceName),fhir 49hr (select ResourceName, count(*) as Count from Ids, Types where Ids.ResourceTypeKey = Types.ResourceTypeKey group by ResourceName),fhir 49hr (select ResourceName, count(*) as Count from Ids, Types where Ids.ResourceTypeKey = Types.ResourceTypeKey group by ResourceName),fhir 49hr (select ResourceName, count(*) as Count from Ids, Types where Ids.ResourceTypeKey = Types.ResourceTypeKey group by ResourceName),fhir 48hr (select ResourceName, count(*) as Count from Ids, Types where Ids.ResourceTypeKey = Types.ResourceTypeKey group by ResourceName),fhir 48hr (select ResourceName, count(*) as Count from Ids, Types where Ids.ResourceTypeKey = Types.ResourceTypeKey group by ResourceName),Operation/Read 48hr (select Ids.ResourceKey, Deleted from Ids, Types where Ids.id = :s and Ids.ResourceTypeKey = Types.ResourceTypeKey and Supported = 1 and ResourceName = :n),Operation/Operation 47hr (),Operation/Search 47hr (select ResourceTypeKey from Types where supported = 1 and ResourceName = 'Patient'))

с чем это может быть связано?

**Comment by Semalexa** [comment]
Алексей,
у создателей FHIR тоже пока что с этой ошибкой сборка падает (см. [их историю сборок](https://travis-ci.org/hl7-fhir/fhir-svn/builds) - две последних сборки https://travis-ci.org/hl7-fhir/fhir-svn/builds/120301678#L844 и https://travis-ci.org/hl7-fhir/fhir-svn/builds/120503462#L844). 
Вот [тут](https://chat.fhir.org/#narrow/stream/committers/topic/ci-notifications) можно посмотреть, что они об этом пишут. Судя по фразе
James Agnew: `@Grahame Grieve is something up with your server? I think this is a terminology lookup thing of some sort..`, 
что-то случилось с сервером Грэма Грива. Надо подождать, пока они починят. Пока что можно просто стянуть последнюю версию рус. перевода (сегодняшнюю), вносить свои правки в файлы и коммитить, не пытаясь собрать версию.

**Comment by Bolik** [comment]
Александра, не удается закоммитить в мастер. Не могли бы вы продублировать приглашение? Спасибо

**Comment by Semalexa** [comment]
Отменила pending invitation и отправила вам новое приглашение.

---
Sincerely,
Alexandra

**Comment by Bolik** [comment]
Спасибо, все получилось. Есть ли какие-то соглашения о сообщениях в commit log?

**Comment by Semalexa** [comment]
Отлично!

Я стараюсь придерживаться вот этого способа:
http://seesparkbox.com/foundry/semantic_commit_messages.

fix: dot in claim-spreadsheet.xml
fix: tag in timelines.html
translate: claim codesystem conceptmap
update: fhir version - part 1


---
Sincerely,
Alexandra
